### PR TITLE
DJ 2022 edits and news

### PR DESCRIPTION
**Pull request by ringisd**

### CODE REVIEW

**Comment by ringisd** [comment]
You can ignore the changes to the gemfiles. I was lazy and did add all and commit all and did not realise that those changed when I was setting things up

**Comment by seblemaguer** [comment]
@ringisd could you remove the gemfiles and rebase? that would be easier and cleaner. 

thanks

**Comment by ringisd** [comment]
@seblemaguer I think I did it. There is still one extra blank line in gemfile. I also added Meegan Gower to PhD's

**Comment by vibhoothi** [comment]
Whoops, needs some cleanups to get it working, let me try locally

**Review by vibhoothi — APPROVED** [review]
I cleanup the commits locally and updated the PR, 

Thanks for the edits, hopefully we can have it in revamped site soon, 

I did not deploy it locally due to RVM issue, but I hope it worked for you when you testd

**Pull request merged**
