### PR TITLE
Modernize the Sigmedia 2022 Edition

### PR DESCRIPTION
**Pull request by vibhoothi**
This is a large MR, 

This tries to change the whole Ui/UX of the current website, I tried to keep the URLs almost same and things, but internally I have changed some locations of files for better structure, 

This patchset is based on a RT2 lab website,

The long-term goal is, land this patchset after review, and then work on adding more content based on this template as our old template is too pale to work on new cosmetic changes. 

~Will update deployments to GitHub Actions and will update the MR with dmeo URL, once it is ready, till then marking MR as WIP.~
Edit:

Deployment: ~https://deploy-v2-test.vercel.app/~
https://sigmedia-transform.netlify.app/

We actually do not need to overengineer with GitHub Actions as normal github deployment will be fast and robust enough for our usecase. 
As it is fork, we will not get the CSS directly wokring in github deployment, so used ~vercel~ Netlify, to cross-check, tested github deployment here: https://vibhoothi.github.io/

### CODE REVIEW

**Comment by vibhoothi** [comment]
~Demo SIte: https://sigmedia-tv-transform-vibhoothi.vercel.app/~

https://sigmedia-transform.netlify.app/

**Comment by vibhoothi** [comment]
Screenshots: 
image
image
image

**Comment by seblemaguer** [comment]
sorry, won't have time to review this

**Comment by seblemaguer** [comment]
I added some comments on some part of the new website and I have some comments:
  - I don't like the orange, I find it unreadable but that is a personal opinion.
  - The team page looks awesome but is very slow to load on my side (could be a server thing)
  - We should think about a way of automatically loading all the bibtex files in an efficient way (now, it is totally non-efficient and if I am not mistaken your version still has the manual loading issue)
  - Some pages are a bit cluttered
    - the blog page should be reformatted to make it more readable
    - I have difficulties to distinguish between the different header levels

Obviously, you should check everything with the academic staff (Anil, Francois, Naomi and Angeliki) as they are the one making the decisions for the website.

Lots of work done I see :)

**Comment by seblemaguer** [comment]
We discussed a bit about this with @frcs. Could you split your PR into 2 PRs:
  - one containing the content/architecture modifications
  - one containing the rendering/formatting modifications

Thanks,
Seb

**Comment by vibhoothi** [comment]
> We discussed a bit about this with @frcs. Could you split your PR into 2 PRs:
> 
> * one containing the content/architecture modifications
> * one containing the rendering/formatting modifications
> 
> Thanks, Seb

Hi, 

If I understand correctly, you are advising to have one MR to have file-movement to new structure but keeping the old-style of UI, second MR is to have new UI/UX,

I tried to see like that, but seems to be quite non-trivial thing to split the whole work-package into two like you requested, if you check each commits, it does both together, 
https://github.com/sigmedia/sigmedia.github.io/pull/17/commits/98f5a8ae597ea7b787bcf1a4e1efb779a1b271ba
For instance this commit,
The reason for this way is, we are migrating to a new template as a whole, if we split the each of them into two, then it might be non-functional. Or will have to work heavily to have the old-template and things in the old-style with different paths?

**Comment by vibhoothi** [comment]
Hi, 
I have tried to address the review comments finally
+ Made to Trinity Blue, so less annoying orange,
+ Custom designed the header levels to have more distinct levels,
+ Rest of the things like bibtex and comments we could potentially address it later after having this changes. 

The Demo sites have updated and also screenshots in the above comments.
> Note: Current website already have this problem of non-distinguishable titles and headlines, 

Screenshots:

Current: 
image
https://sigmedia.github.io/speech/2018/04/18/uk-speech.html

Proposed: 
image
https://vibhoothi.github.io/speech/2018/04/18/uk-speech.html

**Comment by vibhoothi** [comment]
New Color code with Trinity blue
image

image

**Review by frcs — APPROVED** [review]
Looking good. Minor changes when it comes to style could be fixed later on.

**Pull request merged**
